### PR TITLE
feat: file level events

### PR DESCRIPTION
**Pull request by meetmangukiya**
Diff seems pretty huge. Something seems off. I did `tree-sitter generate` with `tree-sitter-cli 0.22.6`. Pushing just the code change.

### CODE REVIEW

**Comment by JoranHonig** [comment]
Thanks!

Yeah, it's much easier if you don't run tree-sitter generate. Not a big fan of having all those standard generated files all over the place & having them clutter diffs 😅 .

Would you be open to adding a test case for this change?

**Comment by meetmangukiya** [comment]
Added a simple test, can avoid duplicating all 4 cases on file level events i think?

**Comment by clason** [comment]
> . Not a big fan of having all those standard generated files all over the place & having them clutter diffs 😅 .

Then you should remove them from the repo and force downstream to generate themselves. Keeping outdated generated files in your repo is the worst of all possible worlds.

(But if your grammar requires node -- which I don't think is the case here from a quick glance -- you should at least commit `grammar.json`, which is small, has meaningful diffs, and can be used to generate the parser from without node (via `tree-sitter generate src/grammar.json`)).

**Comment by JoranHonig** [comment]
@clason unfortunately this is how a lot of the tree-sitter ecosystem parser distribution is done, so I'll have to keep it this way 

Initially I'd kept the generated files separate, but that broke things, so here we are.

**Review by JoranHonig — APPROVED** [review]
lgtm

Thanks for the contribution @meetmangukiya

**Comment by clason** [comment]
> @clason unfortunately this is how a lot of the tree-sitter ecosystem parser distribution is done, so I'll have to keep it this way

Sorry, but I don't see how this implies that you must not keep them in sync. Repos (throughout the ecosystem!) either
1. track `parser.c`, and commits change both grammar and parser (you know you can mark them as "generated" in `.gitattributes` to hide their diff in PRs, right?) or
2. omit `parser.c` and tell users to generate it themselves as part of their "build".

Both options are perfectly fine, but if there is a parser but I can't rely on it being up-to-date, this is basically the same as option 2, except that I have to find about it the hard way when I get issues about unexpected behavior.

**Comment by JoranHonig** [comment]
Hey @clason I did not know about (2).

I was thinking about adding a gh action in this repo to update the generated files if there is an update to the grammar, wyt about an approach like that?

I'm assuming the time it takes to generate & commit the new files doesn't create too much of an issue for downstream projects.

**Comment by clason** [comment]
> I'm assuming the time it takes to generate & commit the new files doesn't create too much of an issue for downstream projects.

It's more about consistent repo state for bisecting. But yes, we don't track every individual commit, so the chance of hitting an "outdated" commit are fairly small (but not zero).

(Just to explain: nvim-treesitter -- which I maintain -- offers users the possibility of installing from parser (when available) _or_ from grammar (e.g., if a parser is too old and uses a no longer supported ABI). If these give two different -- possibly incompatible w.r.t. queries! -- parsers, we're in trouble ;)

> I was thinking about adding a gh action in this repo to update the generated files if there is an update to the grammar, wyt about an approach like that?

Honestly, I wouldn't spend too much time DIY something like that and instead rely on upstream workflows (https://github.com/tree-sitter/workflows). The official tree-sitter policy is moving towards "keep parsers out of repos but include them in versioned release artifacts (you _do_ make semantically versioned releases, right? ;))" and will include tooling (`tree-sitter release`) and workflows for that in one of the next two versions -- after which there'll be a general push across the ecosystem to follow that policy.

**Comment by JoranHonig** [comment]
> The official tree-sitter policy is moving towards "keep parsers out of repos but include them in versioned release artifacts (you do make semantically versioned releases, right? ;))" and will include tooling (tree-sitter release) and workflows for that in one of the next two versions -- after which there'll be a general push across the ecosystem to follow that policy.

That's perfect! 

All right here is what I'll do:

1. I've changed the current gh actions to ensure that the autogenerated files provided in a pr match the result of a fresh generate
2. I'll wait for the new release flow and adopt that once it's available

**Pull request merged**
