### PR TITLE
feat(docs): interactive parser playground (#2)

### PR DESCRIPTION
**Pull request by sambacha**
Hello, just wanted to share this don't have to merge this PR. This adds the playground functionality you see for other languages on the tree sitter webpage for solidity. Utilizes jekyll + wasm generated parser. Only caveats are renaming the wasm file output to all lowercase and building the jekyll site on a local machine, github pages won't work.

> [https://sambacha.github.io/tree-sitter-solidity/](https://sambacha.github.io/tree-sitter-solidity/)

Cheers

### CODE REVIEW

**Comment by JoranHonig** [comment]
Wow! This is really cool!

@sambacha you've already done a lot but if you have time it'd be super helpful. I'm thinking of setting up the following:
1. create a branch on this repo `interactive_playground` with the code for building the website
2. create a github action that triggers on pushes to master which
  a. clones the `interactive_playground`
  b. clones `master`
  c. builds & deploys to gh pages 
  
Once I have that I'll give you a ping to review!
  
In addition to that, I'll probably also want to leverage the rust code & config to deploy a tree-sitter-solidity as a package.

**Comment by sambacha** [comment]
sounds great, additionally, if you do decide to leverage rust you should check out this: https://github.com/afnanenayet/diffsitter  it will enable you to utilize tree-sitter as an AST-based diff tool so that you can get meaningful semantic diffs.

Let me know how I can help, 

Cheers,

Sam

**Comment by sambacha** [comment]
revisiting this actually

**Comment by sambacha** [comment]
Do you have any preference for Editor Styling? Here is an updated look https://sambacha.github.io/solidity-parser-explorer

**Comment by JoranHonig** [comment]
Hey Sam,

I'm really sorry for being so slow to respond. I have too many side projects 🙈 

I don't have strong styling preferences. Though having the ast in a box with isolated scrolling is definitely helpful!

Also thanks for the reference to diffsitter, really cool!

**Pull request closed without merging**
