### PR TITLE
Feat: include d.ts typings for parser

### PR DESCRIPTION
**Pull request by sambacha**
auto-generated .d.ts file for types
also updated dependencies 

d.ts was generated using https://github.com/asgerf/dts-tree-sitter

### CODE REVIEW

**Comment by JoranHonig** [comment]
this is really cool! 

Do you ever need to manually update the generated .d.ts file? If not then I'm thinking we should put this in CI and automatically generate it on every deployment.

WDYT?

**Comment by sambacha** [comment]
> this is really cool!
> 
> Do you ever need to manually update the generated .d.ts file? If not then I'm thinking we should put this in CI and automatically generate it on every deployment.
> 
> WDYT?

Wanted to see your thoughts before adding anything else, was unsure about it. Happy to add it to CI. Can add it this week, additionally will have to add typescript config and versions in case a new version of ts introduces breaking changes/etc and maybe an example of usage

**Comment by JoranHonig** [comment]
Hmm I'm thinking that the types should maybe be part of a separate npm package. 

That way the dependencies of the main module stay clean.

**Comment by JoranHonig** [comment]
I'm going to close this pr

I think this is really cool but I'm afraid of adding a dependency on a small project like this.

obligatory xkcd meme: https://xkcd.com/2347/

**Pull request closed without merging**
