### PR TITLE
Add body to struct and enum declarations

### PR DESCRIPTION
**Pull request by beeb**
Adding a body to struct and enum declarations allows to easily create queries to match inside a type definition (the curly braces and everything inside).

This is required to write the proper textobject queries for helix, which I'm currently doing.

I was not able to re-generate the python bindings, maybe you can help me or do it for me?

### CODE REVIEW

**Review by JoranHonig — APPROVED** [review]
LGTM, I'll regenerate the bindings with the next release

**Comment by beeb** [comment]
Thanks! Not sure about the CI errors.

**Comment by JoranHonig** [comment]
fixed the CI errors in master, if you pull the ci checks should pass

**Comment by beeb** [comment]
Done and thanks! :)

**Comment by beeb** [comment]
I had a small issue with one test, but should be fixed now and I also merged the changes from main

**Comment by JoranHonig** [comment]
lol, this is such a coincidence

**Comment by beeb** [comment]
I see you included the changes in #56 so all good, feel free to close!

**Comment by JoranHonig** [comment]
I just merged your commits separately with a quick fix which mirrors: https://github.com/JoranHonig/tree-sitter-solidity/pull/50/commits/0424fe7d8debfa75661b343c06b2a171229499f3

https://github.com/JoranHonig/tree-sitter-solidity/pull/56

Thanks for the contribution!

**Pull request closed without merging**
