### PR TITLE
fix: typo in event_parameter

### PR DESCRIPTION
**Pull request by beeb**
While writing the `textobject` queries for [helix editor](https://github.com/helix-editor/helix), I noticed a spelling mistake in event parameters.

### CODE REVIEW

**Review by JoranHonig — APPROVED** [review]

**Comment by beeb** [comment]
I merged main, but the CI needs approval to run

**Comment by beeb** [comment]
Hey @JoranHonig , any chance we could merge my two PRs soon? I would love to submit a PR to helix taking benefit from these changes.

**Comment by JoranHonig** [comment]
It's merged now! Thanks for the contribution

**Comment by beeb** [comment]
Already in helix master :) https://github.com/helix-editor/helix/pull/10318

**Pull request merged**
